Repository openstack-k8s-operators/ovn-operator, pull requests merged in 2023-05, with the labels that each got.

#46 Dynamic serviceaccount/role/rolebinding creation
  api/go.mod
  api/go.sum
  api/v1beta1/ovndbcluster_types.go
  api/v1beta1/ovnnorthd_types.go
  config/rbac/role.yaml
  config/rbac/service_account.yaml
  controllers/ovndbcluster_controller.go
  controllers/ovnnorthd_controller.go
  go.mod
  go.sum
  pkg/ovndbcluster/const.go
  pkg/ovndbcluster/statefulset.go
  pkg/ovnnorthd/const.go
  pkg/ovnnorthd/deployment.go
  tests/kuttl/common/assert_sample_deployment.yaml
Labels: approved, lgtm

#40 Replace TripleO images by TCIB images
  Makefile
  config/default/manager_default_images.yaml
  config/samples/ovn_v1beta1_ovndbcluster.yaml
  config/samples/ovn_v1beta1_ovndbcluster_nb.yaml
  config/samples/ovn_v1beta1_ovndbcluster_sb.yaml
  config/samples/ovn_v1beta1_ovnnorthd.yaml
  tests/kuttl/common/assert_sample_deployment.yaml
Labels: lgtm

#42 Enable ginkgolinter
  .golangci.yaml
Labels: approved, lgtm

#48 Adapt to split test helpers in lib-common
  api/bases/ovn.openstack.org_ovndbclusters.yaml
  api/bases/ovn.openstack.org_ovnnorthds.yaml
  api/go.mod
  api/go.sum
  config/crd/bases/ovn.openstack.org_ovndbclusters.yaml
  config/crd/bases/ovn.openstack.org_ovnnorthds.yaml
  go.mod
  go.sum
  tests/functional/suite_test.go
Labels: approved, lgtm

#50 Add renovate.json for deps update
  renovate.json
Labels: approved

#51 Webhook cleanup
  Makefile
  api/go.mod
  api/go.sum
  api/v1beta1/common.go
  api/v1beta1/ovndbcluster_types.go
  api/v1beta1/ovnnorthd_types.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm

#52 Merge ovs-operator logic into ovn-operator
  Makefile
  PROJECT
  api/bases/ovn.openstack.org_ovncontrollers.yaml
  api/v1beta1/common.go
  api/v1beta1/ovncontroller_types.go
  api/v1beta1/ovncontroller_webhook.go
  api/v1beta1/webhook_suite_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/ovn.openstack.org_ovncontrollers.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_ovncontrollers.yaml
  config/crd/patches/webhook_in_ovncontrollers.yaml
  config/default/manager_default_images.yaml
  config/rbac/ovncontroller_editor_role.yaml
  config/rbac/ovncontroller_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/ovn_v1beta1_ovncontroller.yaml
  config/webhook/manifests.yaml
  controllers/ovncontroller_controller.go
  go.mod
  go.sum
  hack/clean_local_webhook.sh
  hack/configure_local_webhook.sh
  main.go
  pkg/ovncontroller/configjob.go
  pkg/ovncontroller/const.go
  pkg/ovncontroller/daemonset.go
  pkg/ovncontroller/network.go
  pkg/ovncontroller/utils.go
  pkg/ovncontroller/volumes.go
  templates/ovncontroller/bin/init.sh
  templates/ovncontroller/bin/start-ovsdb-server.sh
  tests/functional/base_test.go
  tests/functional/ovncontroller_controller_test.go
  tests/functional/suite_test.go
  tests/kuttl/common/assert_sample_deployment.yaml
  tests/kuttl/common/cleanup-ovn.yaml
  tests/kuttl/common/deploy_ovn.yaml
  tests/kuttl/common/errors_cleanup_ovn.yaml
  tests/kuttl/tests/ovn_scale/05-errors.yaml
  tests/kuttl/tests/ovn_scale/05-scale-down-pods-ovncontroller.yaml
  tests/kuttl/tests/ovn_scale/06-cleanup-ovn.yaml
  tests/kuttl/tests/ovn_scale/06-errors.yaml
Labels: approved, lgtm

#62 GetDBEndpoints: handle case of len(dbClusters) == 1
  api/v1beta1/client.go
Labels: approved, lgtm

#63 Fix OVNController KClient nil-pointer error
  main.go
Labels: approved, lgtm
