Repository openstack-k8s-operators/ovn-operator, pull requests merged in 2024-04, with the labels that each got.

#233 Split ovn-controller in separate daemonsets
  api/bases/ovn.openstack.org_ovncontrollers.yaml
  api/v1beta1/ovncontroller_types.go
  config/crd/bases/ovn.openstack.org_ovncontrollers.yaml
  controllers/ovncontroller_controller.go
  pkg/ovncontroller/configjob.go
  pkg/ovncontroller/daemonset.go
  pkg/ovncontroller/volumes.go
  templates/ovncontroller/bin/net_setup.sh
  tests/functional/base_test.go
  tests/functional/ovncontroller_controller_test.go
  tests/kuttl/common/assert_sample_deployment.yaml
  tests/kuttl/common/errors_cleanup_ovn.yaml
Labels: approved, lgtm, ok-to-test

#248 Handle the physical network changes "ovn-bridge-mappings"
  config/samples/nad_datacentre2.yaml
  config/samples/nad_datacentre3.yaml
  templates/ovncontroller/bin/functions
  tests/kuttl/common/cleanup-ovn.yaml
  tests/kuttl/tests/ovn_nicmappings/01-assert.yaml
  tests/kuttl/tests/ovn_nicmappings/01-deploy-ovn.yaml
  tests/kuttl/tests/ovn_nicmappings/02-new-network-attachment-definition.yaml
  tests/kuttl/tests/ovn_nicmappings/03-assert.yaml
  tests/kuttl/tests/ovn_nicmappings/03-nicmappings-patch-datacentre2.yaml
  tests/kuttl/tests/ovn_nicmappings/04-assert.yaml
  tests/kuttl/tests/ovn_nicmappings/04-nicmappings-patch-datacentre3.yaml
  tests/kuttl/tests/ovn_nicmappings/06-cleanup-ovn.yaml
  tests/kuttl/tests/ovn_nicmappings/06-errors.yaml
Labels: approved, lgtm, ok-to-test

#264 No-op, build with latest ovn images
  tests/functional/base_test.go
Labels: approved

#262 Revert "Add support for adding multiple networkattachments to the ovn…
  api/bases/ovn.openstack.org_ovncontrollers.yaml
  api/v1beta1/ovncontroller_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/ovn.openstack.org_ovncontrollers.yaml
  controllers/ovncontroller_controller.go
  tests/functional/ovncontroller_controller_test.go
Labels: approved, lgtm, ok-to-test

#265 Fix ovn_controller tls args
  pkg/ovncontroller/daemonset.go
Labels: approved, lgtm

#259 Remove raftAddress from CRD
  api/bases/ovn.openstack.org_ovndbclusters.yaml
  api/v1beta1/ovndbcluster_types.go
  config/crd/bases/ovn.openstack.org_ovndbclusters.yaml
  controllers/ovndbcluster_controller.go
  tests/functional/ovndbcluster_controller_test.go
Labels: approved, lgtm

#267 Remove the double update when finalizer added
  controllers/ovndbcluster_controller.go
  controllers/ovnnorthd_controller.go
Labels: approved, lgtm

#261 Set ObservedGeneration after condition init
  controllers/ovncontroller_controller.go
  controllers/ovndbcluster_controller.go
  controllers/ovnnorthd_controller.go
Labels: approved, lgtm

#273 Ensure golangci-lint runs on all files
  .pre-commit-config.yaml
  api/v1beta1/client.go
  controllers/ovncontroller_controller.go
  controllers/ovndbcluster_controller.go
  controllers/ovnnorthd_controller.go
  main.go
  pkg/ovncontroller/configjob.go
  pkg/ovncontroller/const.go
  pkg/ovnnorthd/const.go
  tests/functional/base_test.go
  tests/functional/ovncontroller_controller_test.go
  tests/functional/ovndbcluster_controller_test.go
  tests/functional/ovnnorthd_controller_test.go
  tests/functional/suite_test.go
Labels: approved, lgtm

#269 Remove networkAttachment for ovnNorthd
  api/bases/ovn.openstack.org_ovnnorthds.yaml
  api/v1beta1/ovnnorthd_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/ovn.openstack.org_ovnnorthds.yaml
  controllers/ovnnorthd_controller.go
  go.mod
  go.sum
  pkg/ovnnorthd/deployment.go
  tests/functional/ovnnorthd_controller_test.go
Labels: approved, lgtm

#276 Fix default handling for LogLevel param
  api/v1beta1/ovndbcluster_types.go
  api/v1beta1/ovnnorthd_types.go
  tests/functional/base_test.go
Labels: approved, lgtm

#275 DBCluster: remove explicit status update
  controllers/ovndbcluster_controller.go
Labels: approved, lgtm
